gems:
  - jekyll-mentions
  - jekyll-sitemap

footer-links:
  github: nicolasbock

pages_list:
  Main: "/data-sets"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

url: http://www.freeon.org/data-sets
baseurl: "/data-sets"
